"""update name tables in tables.tables

Revision ID: b969a8838c1c
Revises: e036c13994f3
Create Date: 2021-04-01 10:56:41.612031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b969a8838c1c'
down_revision = 'e036c13994f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courseroom',
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], )
    )
    op.create_table('pstudentcourse',
    sa.Column('pstudent_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['pstudent_id'], ['pstudent.id'], )
    )
    op.drop_table('Tpstudentcourse')
    op.drop_table('Tcourseroom')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tcourseroom',
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='Tcourseroom_course_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='Tcourseroom_student_id_fkey')
    )
    op.create_table('Tpstudentcourse',
    sa.Column('pstudent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='Tpstudentcourse_course_id_fkey'),
    sa.ForeignKeyConstraint(['pstudent_id'], ['pstudent.id'], name='Tpstudentcourse_pstudent_id_fkey')
    )
    op.drop_table('pstudentcourse')
    op.drop_table('courseroom')
    # ### end Alembic commands ###
